import { test, expect } from "bun:test";
import { setTimeout as delay } from "node:timers/promises";
import { createAudioDecoder } from "../../src/perception/audio/decoder";

test("Opus decoder warm-up does not move a sound back to the first received packet", async () => {
  // Generated by the Go audio consumer: alternating 20/40 ms silence, 1.2 s total,
  // with its declared 80 ms Opus pre-skip. No microphone recording is used.
  const bytes = new Uint8Array(
    await Bun.file(
      new URL("./fixtures/opus-silence.ogg", import.meta.url),
    ).arrayBuffer(),
  );
  const anchorReceivedAt = Date.now();
  let first: number | undefined;
  let failure: unknown;
  const decoder = createAudioDecoder({
    config: {
      firstFrameTimeoutMs: 3000,
      silenceTimeoutMs: 3000,
      maxFrameAgeMs: 2000,
    },
    executable: process.env.PERCEPTION_FFMPEG_PATH ?? "ffmpeg",
    async open() {
      return {
        stream: new ReadableStream<Uint8Array>({
          start(controller) {
            controller.enqueue(bytes);
          },
        }),
        format: "ogg" as const,
        generation: crypto.randomUUID(),
        anchorReceivedAt,
        decodedStartOffsetMs: 80,
      };
    },
    onMedia() {},
    async onPcm(_samples, observedAt) {
      first ??= observedAt;
    },
  });
  decoder.completed.catch((error: unknown) => {
    failure = error;
  });
  try {
    const deadline = performance.now() + 4000;
    const pending = () => first === undefined && failure === undefined;
    while (pending() && performance.now() < deadline) await delay(10);
    expect(failure).toBeUndefined();
    expect(first).toBe(anchorReceivedAt + 80);
  } finally {
    await decoder.close();
  }
}, 10000);
