import {
  Database,
  Radio,
  Bot,
  LayoutGrid,
  Users,
  ScrollText,
  Settings2,
  Video,
  Waypoints,
} from "lucide-react";

export const navigation = [
  {
    to: "/agent",
    label: "AI",
    icon: Bot,
    cornerRadius: 14,
    mobilePrimary: false,
  },
  {
    to: "/devices",
    label: "房间",
    icon: LayoutGrid,
    cornerRadius: 14,
    mobilePrimary: true,
  },
  {
    to: "/spaces",
    label: "空间",
    icon: Waypoints,
    cornerRadius: 14,
    mobilePrimary: false,
  },
  {
    to: "/members",
    label: "成员",
    icon: Users,
    cornerRadius: 14,
    mobilePrimary: true,
  },
  {
    to: "/cameras",
    label: "看家",
    icon: Video,
    cornerRadius: 22,
    mobilePrimary: true,
  },
  {
    to: "/device-logs",
    label: "日志",
    icon: ScrollText,
    cornerRadius: 10,
    mobilePrimary: false,
  },
  {
    to: "/data",
    label: "DB",
    icon: Database,
    cornerRadius: 14,
    mobilePrimary: false,
  },
  {
    to: "/agent-context",
    label: "数据",
    icon: Radio,
    cornerRadius: 14,
    mobilePrimary: false,
  },
  {
    to: "/settings",
    label: "设置",
    icon: Settings2,
    cornerRadius: 18,
    mobilePrimary: false,
  },
] as const;
