const categoryLabels = new Map([
  ["air-conditioner", "空调"],
  ["air-fresh", "新风机"],
  ["air-monitor", "空气检测仪"],
  ["air-purifier", "空气净化器"],
  ["bath-heater", "浴霸"],
  ["cooker", "电饭煲"],
  ["curtain", "窗帘"],
  ["dehumidifier", "除湿机"],
  ["diffuser", "调香机"],
  ["fan", "风扇"],
  ["gateway", "网关"],
  ["kettle", "电水壶"],
  ["light", "灯"],
  ["lock", "门锁"],
  ["massager", "按摩仪"],
  ["mosquito-dispeller", "驱蚊器"],
  ["motion-sensor", "人体传感器"],
  ["occupancy-sensor", "人在传感器"],
  ["nas", "存储设备"],
  ["night-light", "夜灯"],
  ["outlet", "插座"],
  ["pet-feeder", "宠物喂食器"],
  ["remote-control", "遥控器"],
  ["safe-box", "保管箱"],
  ["speaker", "音箱"],
  ["submersion-sensor", "水浸传感器"],
  ["switch", "开关"],
  ["temperature-humidity-sensor", "温湿度计"],
  ["vacuum-cleaner", "吸尘器"],
  ["water-purifier", "净水器"],
]);
export function deviceCategoryLabel(category: string) {
  return categoryLabels.get(category) ?? category;
}
